---
- name: Install cRPD on servers
  hosts: juniper
  gather_facts: no
  connection: local
  roles:
    - Juniper.junos

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Display facts
    debug:
       var: hostvars[inventory_hostname]
       verbosity: 2

  - name: Display hostname
    debug:
       msg: set system hostname {{ aliase }}

  - name: "set hostname"
    juniper_junos_config:
       user: "{{ junos_username }}"
       passwd: "{{ junos_passwd }}"
       comment: "set hostname"
       config_mode: "private"
       load: "set"
       lines:
         - "set system host-name {{ aliase }}"
    register: response

  - name: "Print the config changes"
    debug:
       var: response.diff_lines

